spring:
  application:
    name: union-talk-file
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  config:
    import:
      - classpath:config.yaml
      - nacos:union-talk-datasource.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:union-talk-rabbitmq.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:union-talk-seata.yaml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:union-talk-file.yaml?group=DEFAULT_GROUP&refreshEnabled=true
