import type {
  Conversation,
  NotificationItem,
  ProfileSettings,
} from '@/pages/home/model/types'

export const initialProfile: ProfileSettings = {
  userId: 'local-user-1',
  code: 'UT1001',
  displayName: 'Devin',
  email: 'devin@example.com',
  avatarUrl: '',
  bio: '保持清晰沟通，快速同步产品和工程进展。',
  needFriendVerify: true,
  status: '在线',
  lastLoginAt: '今天 11:32',
  privacyLabel: '仅好友可见',
  trustedDeviceList: [
    {
      id: 'macbook-local',
      name: 'MacBook Pro',
      location: '上海',
      lastActive: '当前在线',
      isCurrent: true,
    },
    {
      id: 'iphone-local',
      name: 'iPhone',
      location: '上海',
      lastActive: '昨天 21:18',
      isCurrent: false,
    },
  ],
}

export const initialConversationList: Conversation[] = [
  {
    id: 'group-product',
    kind: 'group',
    name: '产品体验群',
    description: '产品、设计、前端的日常协作群',
    status: '正常',
    lastMessage: '我们先把四列布局定下来，再接真实数据。',
    lastActive: '2 分钟前',
    unreadCount: 4,
    memberList: [
      { id: 'group-product-qiao', name: '乔安', role: 'owner' },
      { id: 'group-product-lin', name: '林澈', role: 'member' },
      { id: 'group-product-zhou', name: '周然', role: 'member' },
      { id: 'group-product-me', name: '我', role: 'member' },
      { id: 'group-product-chen', name: '陈默', role: 'member' },
      { id: 'group-product-su', name: '苏晴', role: 'member' },
      { id: 'group-product-gu', name: '顾言', role: 'member' },
      { id: 'group-product-tang', name: '唐宁', role: 'member' },
      { id: 'group-product-ye', name: '叶舟', role: 'member' },
      { id: 'group-product-shen', name: '沈知', role: 'member' },
      { id: 'group-product-lu', name: '陆远', role: 'member' },
      { id: 'group-product-cheng', name: '程野', role: 'member' },
    ],
    tags: ['Product', 'Design', 'Frontend'],
    accent: 'bg-sky-700 text-white',
    code: 'GROUP-1001',
    relation: '核心协作群',
    isPinned: false,
    isMuted: false,
    isFavorite: true,
    messages: [
      {
        id: 'm-1',
        author: '乔安',
        role: 'Product',
        time: '09:28',
        body: '我希望左侧模块切换不要打断当前阅读节奏，中间列表只负责选择对象。',
      },
      {
        id: 'm-2',
        author: '林澈',
        role: 'Design',
        time: '09:34',
        body: '参考图的信息密度挺合适，详情栏可以作为上下文抽屉，不要一直抢主内容区。',
      },
      {
        id: 'm-3',
        author: '我',
        role: 'Frontend',
        time: '09:41',
        body: '收到。我会先用 mock 数据把切换、详情栏和输入框跑通。',
        tone: 'self',
      },
    ],
  },
  {
    id: 'group-frontend',
    kind: 'group',
    name: '前端协作群',
    description: '组件、路由、样式和测试协作',
    status: '正常',
    lastMessage: 'shadcn 的基础组件补齐之后，页面会更容易维护。',
    lastActive: '18 分钟前',
    unreadCount: 2,
    memberList: [
      { id: 'group-frontend-zhou', name: '周然', role: 'owner' },
      { id: 'group-frontend-lin', name: '林澈', role: 'member' },
      { id: 'group-frontend-chen', name: '陈默', role: 'member' },
      { id: 'group-frontend-me', name: '我', role: 'member' },
      { id: 'group-frontend-qiao', name: '乔安', role: 'member' },
      { id: 'group-frontend-xu', name: '许墨', role: 'member' },
      { id: 'group-frontend-han', name: '韩川', role: 'member' },
    ],
    tags: ['React', 'Vite', 'UI'],
    accent: 'bg-emerald-700 text-white',
    code: 'GROUP-1002',
    relation: '工程协作群',
    isPinned: false,
    isMuted: true,
    isFavorite: false,
    messages: [
      {
        id: 'm-4',
        author: '周然',
        role: 'Frontend',
        time: '10:05',
        body: '我看了一下，按钮和 sonner 已经有了，其余 shadcn primitives 可以按本地风格补。',
      },
      {
        id: 'm-5',
        author: '林澈',
        role: 'Design',
        time: '10:12',
        body: '列表栏保持 280px 左右就行，主内容区要优先保证聊天可读性。',
      },
    ],
  },
  {
    id: 'group-release',
    kind: 'group',
    name: '版本发布群',
    description: '发布节奏、验收和风险同步',
    status: '正常',
    lastMessage: '发布前需要补一次移动端布局检查。',
    lastActive: '昨天',
    unreadCount: 0,
    memberList: [
      { id: 'group-release-chen', name: '陈默', role: 'owner' },
      { id: 'group-release-qiao', name: '乔安', role: 'member' },
      { id: 'group-release-zhou', name: '周然', role: 'member' },
      { id: 'group-release-me', name: '我', role: 'member' },
      { id: 'group-release-lin', name: '林澈', role: 'member' },
      { id: 'group-release-fang', name: '方圆', role: 'member' },
      { id: 'group-release-he', name: '贺宁', role: 'member' },
      { id: 'group-release-zhao', name: '赵清', role: 'member' },
      { id: 'group-release-wu', name: '吴越', role: 'member' },
    ],
    tags: ['Release', 'QA'],
    accent: 'bg-amber-700 text-white',
    code: 'GROUP-1003',
    relation: '发布保障群',
    isPinned: false,
    isMuted: false,
    isFavorite: false,
    messages: [
      {
        id: 'm-6',
        author: '陈默',
        role: 'QA',
        time: '昨天',
        body: '移动端要确认列表和详情抽屉不会互相遮挡。',
      },
    ],
  },
  {
    id: 'friend-lin',
    kind: 'friend',
    name: '林澈',
    description: '产品设计师',
    status: '在线',
    lastMessage: '我把参考图里四列关系标出来了。',
    lastActive: '刚刚',
    unreadCount: 1,
    memberList: [
      { id: 'friend-lin', name: '林澈', role: 'member' },
      { id: 'friend-lin-me', name: '我', role: 'member' },
    ],
    tags: ['Design'],
    accent: 'bg-violet-700 text-white',
    code: 'UT2002',
    relation: '好友 · 设计协作',
    isPinned: false,
    isMuted: false,
    isFavorite: true,
    messages: [
      {
        id: 'm-7',
        author: '林澈',
        role: 'Design',
        time: '11:14',
        body: '左侧 rail 只放最高频入口，不要放太多二级信息。',
      },
      {
        id: 'm-8',
        author: '我',
        role: 'Frontend',
        time: '11:16',
        body: '明白，二级列表交给中栏，主栏只响应当前选中对象。',
        tone: 'self',
      },
    ],
  },
  {
    id: 'friend-zhou',
    kind: 'friend',
    name: '周然',
    description: '前端工程师',
    status: '30 分钟前在线',
    lastMessage: 'Dropdown 和 Sheet 可以先做本地状态。',
    lastActive: '30 分钟前',
    unreadCount: 0,
    memberList: [
      { id: 'friend-zhou', name: '周然', role: 'member' },
      { id: 'friend-zhou-me', name: '我', role: 'member' },
    ],
    tags: ['Frontend'],
    accent: 'bg-teal-700 text-white',
    code: 'UT2003',
    relation: '好友 · 工程协作',
    isPinned: false,
    isMuted: false,
    isFavorite: false,
    messages: [
      {
        id: 'm-9',
        author: '周然',
        role: 'Frontend',
        time: '10:44',
        body: '先别接接口，后续把 mock 数据替换成 service 就行。',
      },
    ],
  },
  {
    id: 'friend-qiao',
    kind: 'friend',
    name: '乔安',
    description: '产品经理',
    status: '勿扰',
    lastMessage: '通知详情里要能看到来源和处理状态。',
    lastActive: '1 小时前',
    unreadCount: 3,
    memberList: [
      { id: 'friend-qiao', name: '乔安', role: 'member' },
      { id: 'friend-qiao-me', name: '我', role: 'member' },
    ],
    tags: ['Product'],
    accent: 'bg-rose-700 text-white',
    code: 'UT2004',
    relation: '好友 · 产品协作',
    isPinned: false,
    isMuted: true,
    isFavorite: false,
    messages: [
      {
        id: 'm-10',
        author: '乔安',
        role: 'Product',
        time: '09:58',
        body: '通知不是聊天，所以主栏底部不要显示输入框。',
      },
    ],
  },
]

export const initialNotificationList: NotificationItem[] = [
  {
    id: 'notice-release',
    title: '版本更新提醒',
    source: 'Union Talk 系统',
    time: '今天 10:20',
    summary: '桌面端首页布局进入本地联调阶段。',
    body: '新的首页会先以 mock 数据运行，包含通知、好友、群聊、个人设置和详情抽屉。真实接口将在布局验收后接入。',
    status: '未读',
    unread: true,
    category: '系统通知',
    actionHint: '确认后可标记为已处理，后续接入服务端状态。',
  },
  {
    id: 'notice-friend',
    title: '好友申请',
    source: '林澈',
    time: '今天 09:12',
    summary: '林澈希望与你同步首页导航方案。',
    body: '对方已发送好友申请。当前版本只展示申请详情，后续会接入同意和拒绝动作。',
    status: '待处理',
    unread: true,
    category: '好友申请',
    actionHint: '当前仅做本地处理演示，不会发送同意或拒绝请求。',
  },
  {
    id: 'notice-group',
    title: '群聊邀请',
    source: '前端协作群',
    time: '昨天 18:40',
    summary: '你被邀请加入前端协作群。',
    body: '这个群用于同步组件库、布局实现、测试补充和发布前检查。',
    status: '已读',
    unread: false,
    category: '群聊邀请',
    actionHint: '邀请处理将在后续接入群聊服务后开放。',
  },
]
