spring:
  rabbitmq:
    host: ${UNION_RABBITMQ_HOST:127.0.0.1}
    port: ${UNION_RABBITMQ_PORT:5672}
    username: ${UNION_RABBITMQ_USERNAME:xxx}
    password: ${UNION_RABBITMQ_PASSWORD:xxx}
    virtual-host: ${UNION_RABBITMQ_VIRTUAL_HOST:/union_talk}
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
