server:
  port: ${SERVER_PORT:13005}
  servlet:
    context-path: /api/v1

grpc:
  server:
    port: ${UNION_TALK_MESSAGE_GRPC_PORT:19005}
  client:
    union-talk-user:
      address: ${UNION_TALK_USER_GRPC_ADDRESS:discovery:///union-talk-user}
      negotiation-type: plaintext
    union-talk-file:
      address: ${UNION_TALK_FILE_GRPC_ADDRESS:discovery:///union-talk-file}
      negotiation-type: plaintext
