"""Agent Run 业务常量。

Author: devin
GitHub: https://github.com/wzh-devin
Version: 1.0.0
Since: 1.0.0
Created: 2026/07/29 18:46
"""

AGENT_MENTIONED_EVENT_TYPE = "AGENT_MENTIONED"
AGENT_MENTIONED_SCHEMA_VERSION = 1
AGENT_REPLY_IDEMPOTENCY_KEY_PREFIX = "agent-reply:"
AGENT_TRACE_SCHEMA_VERSION = 1
DEFAULT_AGENT_ID = 1
DEFAULT_FIXED_MODEL_ID = "fixed-answer"
DEFAULT_AGENT_RUN_PAGE_SIZE = 20
MAX_AGENT_RUN_PAGE_SIZE = 100
MAX_MODEL_ID_LENGTH = 128
MAX_ANSWER_LENGTH = 100_000
MAX_CITATION_COUNT = 100
MAX_CITATION_KEY_LENGTH = 32
MAX_HEADING_PATH_LENGTH = 1024
DEFAULT_RECENT_MESSAGE_LIMIT = 50
DEFAULT_MAX_CONTEXT_TOKENS = 24_000
DEFAULT_MAX_OUTPUT_TOKENS = 4096
DEFAULT_RECENT_MESSAGE_TOKENS = 5120
DEFAULT_AGENT_SYSTEM_PROMPT = (
    "你是 Union Talk 会话助手。直接回答用户当前问题。"
    "只根据提供的会话和证据回答；证据不足时明确说明，不要编造。"
    "不要主动汇报已收到问题、链路接入、处理流程或其他内部运行状态；"
    "除非用户明确询问这些信息。"
)
LEGACY_INTERNAL_AGENT_REPLY_MARKERS = ("可靠回复链路", "[联调模式]")
DELTA_FLUSH_INTERVAL_SECONDS = 0.08
DELTA_FLUSH_CHARACTER_COUNT = 32
DELTA_MAX_FRAME_BYTES = 8192
